name: Docker Buildx & Push

on:
  push:
    branches:
      - "main"

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      LATEST: "auto"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check if branch is main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo 'LATEST=true' >> "$GITHUB_ENV"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/dattito/volume-backup
          tags: |
            type=ref,event=branch
          flavor: |
            latest=${{ env.LATEST }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
